import os, glob, shutil 

def generate_documentation(output_folder):
    # Clean the output folder
    for filename in glob.glob(f"{output_folder}/*"):
        if os.path.isdir(filename):
            shutil.rmtree(filename)
        else:
            if "00-introduction" not in filename:
                os.remove(filename)

    # Run Doxygen
    os.system(f"cmake . -B/dummy")

    # Delete all files generated by Doxygen that start with _
    for filename in glob.glob("Doxygen/xml/_*"):
        os.remove(filename)

    # Run doxybook2
    os.system(f"doxybook2.exe --input Doxygen/xml --output {output_folder} --config doxybook_config.json")

generate_documentation(output_folder = "../website/docs/api")