import os, glob, shutil 

def generate_documentation(output_folder):
    # Clean the output folder
    for filename in glob.glob(f"{output_folder}/*"):
        if os.path.isdir(filename):
            shutil.rmtree(filename)
        else:
            if "00-introduction" not in filename:
                os.remove(filename)

    # Run Doxygen
    os.system(f"cmake . -B/dummy") # -B/xxx prevents CMake from generating all the build files

    # Delete all files generated by Doxygen that start with _
    for filename in glob.glob("Doxygen/xml/_*"):
        os.remove(filename)

    # Run doxybook2
    os.system(f"doxybook2.exe --input Doxygen/xml --output {output_folder} --config doxybook_config.json --templates doxybook_templates")

    # Remove the "group__" in the filenames and the content of the files
    for filename in glob.glob(f"{output_folder}/**", recursive=True):
        def with_replacement(text):
            return text.replace("group__", "")
        if os.path.isfile(filename):
            with open(filename, 'r+') as f:
                text = f.read()
                f.seek(0)
                f.write(with_replacement(text))
                f.truncate()
        os.rename(filename, with_replacement(filename))

generate_documentation(output_folder = "../website/docs/reference")